# Q33. 错误封装

通常，我们会使用`fmt.Errorf`和`%w`把一个错误封装到另外一个错误里面，如下：

```go
package main

import (
	"errors"
	"fmt"
)

func Func1() error {
	err := errors.New("error from Func1")

	return fmt.Errorf("error from Func2: %w", err)
}

func main() {
	fmt.Println(Func1())
}
```

但在`Go 1.20`中，我们有一个更直接和友好的方法去封装错误，使用`errors.Join()`

```go
package main

import (
	"errors"
	"fmt"
)

func Func1() error {
	err := errors.New("error from Func1")

	return err
}

func Func2() error {
	err := Func1()
	if err != nil {
		return errors.Join(err, errors.New("error from Func2"))
	}

	return nil
}

func main() {
	fmt.Println(Func2())
}
```

